### ISSUE TITLE
Getting issue in generator.py file while running

### ISSUE THREAD

**Issue by vijay-m-hiremath** [clovaai/subword-qac#2]
Traceback (most recent call last):
  File "/home/ext_user2/Vijay/subword-qac-master/generate.py", line 341, in <module>
    main(get_args())
  File "/home/ext_user2/Vijay/subword-qac-master/generate.py", line 337, in main
    generate(model, tokenizer, test_data, args, seen_set=seen_set, calc_mrl=args.calc_mrl)
  File "/home/ext_user2/Vijay/subword-qac-master/generate.py", line 233, in generate
    completions, dls = complete(model, tokenizer, batch, args)
  File "/home/ext_user2/Vijay/subword-qac-master/generate.py", line 193, in complete
    bs_output = beam_search(model, hidden, input, best_scores, off, beam_size, branching_factor, max_suffix_len)
  File "/home/ext_user2/Vijay/subword-qac-master/generate.py", line 160, in beam_search
    tokens[j, 1 - end[j], i] = new_token_idxs[i][j, pos[j, 1 - end[j]]]
  File "/home/ext_user2/.conda/envs/tf_py3/lib/python3.9/site-packages/torch/_tensor.py", line 544, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `logical_not()` operator instead.

**Comment by gyuwankim** [comment]
I guess it came from the different PyTorch versions.
I believe changing 1 - end[j] to ~end[j] will fix this issue.

**Comment by vijaymh5** [comment]
> I guess it came from the different PyTorch versions.
> I believe changing 1 - end[j] to ~end[j] will fix this isszzzzzz

**Comment by vijaymh5** [comment]
> I guess it came from the different PyTorch versions.
> I believe changing 1 - end[j] to ~end[j] will fix this issue.

Hello Mr. Kim,
i tried above solution but din't work.

**Comment by vijay-m-hiremath** [comment]
How we can use generated model in front end?
Any suggestions will be helpful. Thank you.

**Comment by gyuwankim** [comment]
Then, you may cast to the integer type by like 1 - end[j].int().
Could you elaborate more about the front-end?
